global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'flask_backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']