"""Update Association Table Keys

Revision ID: 3949ab3af7ad
Revises: 6dc30aae2ac3
Create Date: 2025-05-30 20:49:13.914283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3949ab3af7ad'
down_revision: Union[str, None] = '6dc30aae2ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed_device', 'id')
    op.drop_column('allowed_skill', 'id')
    op.drop_column('assigned_test', 'id')
    op.drop_column('user_skill', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skill', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('assigned_test', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('allowed_skill', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('allowed_device', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
