"""Update user with email unique constraint

Revision ID: 6dc30aae2ac3
Revises: daebfa9c9919
Create Date: 2025-05-30 18:11:15.322383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc30aae2ac3'
down_revision: Union[str, None] = 'daebfa9c9919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_email', 'user', ['email'], unique=False)
    op.create_index('ix_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_username', table_name='user')
    op.drop_index('ix_email', table_name='user')
    # ### end Alembic commands ###
