"""report-status

Revision ID: fd9c5d8736ea
Revises: 3949ab3af7ad
Create Date: 2025-06-02 06:37:48.618739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9c5d8736ea'
down_revision: Union[str, None] = '3949ab3af7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    review_status = sa.Enum('Pending', 'Approved', 'Rejected', name='review_status')
    review_status.create(op.get_bind(), checkfirst=True)
    op.add_column('test_report', sa.Column('review_status', review_status, nullable=False, server_default='Pending'))
    op.add_column('test_report', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('test_report', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key("test_report_reviewer_id_fkey", 'test_report', 'user', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("test_report_reviewer_id_fkey", 'test_report', type_='foreignkey')
    op.drop_column('test_report', 'reviewer_id')
    op.drop_column('test_report', 'review_comment')
    op.drop_column('test_report', 'review_status')
    # ### end Alembic commands ###
